### ISSUE TITLE
Running in container/codespace

### ISSUE THREAD

**Issue by retog** [factsmission/synospecies#127]
when starting with the "run and debug" VSCode option I get:
```
node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

when staring on the terminal I get the following in the browser:

```
Compiled with problems:
×
ERROR
Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at new WebSocketClient (webpack-internal:///./node_modules/webpack-dev-server/client/clients/WebSocketClient.js:49:19)
    at initSocket (webpack-internal:///./node_modules/webpack-dev-server/client/socket.js:34:12)
    at eval (webpack-internal:///./node_modules/webpack-dev-server/client/index.js?protocol=ws&hostname=172.16.5.4&port=8080&pathname=%2Fws&logging=none&progress=true&overlay=%7B%22errors%22%3Atrue%2C%22warnings%22%3Afalse%7D&reconnect=10&hot=true&live-reload=true:346:55)
    at ./node_modules/webpack-dev-server/client/index.js?protocol=ws&hostname=172.16.5.4&port=8080&pathname=%2Fws&logging=none&progress=true&overlay=%7B%22errors%22%3Atrue%2C%22warnings%22%3Afalse%7D&reconnect=10&hot=true&live-reload=true (https://curly-cod-v6jxg49v6cwwxw-8080.app.github.dev/js/chunk-vendors.js:1418:1)
    at __webpack_require__ (https://curly-cod-v6jxg49v6cwwxw-8080.app.github.dev/js/app.js:1258:33)
    at https://curly-cod-v6jxg49v6cwwxw-8080.app.github.dev/js/app.js:2448:83
    at __webpack_require__.O (https://curly-cod-v6jxg49v6cwwxw-8080.app.github.dev/js/app.js:1307:23)
    at https://curly-cod-v6jxg49v6cwwxw-8080.app.github.dev/js/app.js:2451:53
    at https://curly-cod-v6jxg49v6cwwxw-8080.app.github.dev/js/app.js:2453:12
```

**Comment by nleanba** [comment]
The wrong node option (erroneous `--`) has been fixed in https://github.com/factsmission/synospecies/commit/c04a4193a89994fdf2a8de52e2e9d73006d91268.

The second error only happens when using the dev-server `npm run-script serve`, but not when building (`npm run-script build`).

I have not been able to figure out how to disable webpack-dev-server using websockets. As it build in codespaces and both build & dev-server work locally or in containers, I feel like this isssue can be closed.
